version: "2"

linters:
  default: all
  disable:
    - gosec
    - revive
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
  settings:
    cyclop:
      max-complexity: 17
    funlen:
      lines: 70
    gocognit:
      min-complexity: 40
    lll:
      line-length: 185
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
