name: ci

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Build
        run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Test
        run: go test -v ./...
